-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 18:26:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app_test` ;

-- -----------------------------------------------------
-- Schema app_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_test` DEFAULT CHARACTER SET utf8mb4 COLLATE=utf8mb4_general_ci;
USE `app_test` ;

-- -----------------------------------------------------
-- Table `app_test`.`backend_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_test`.`test` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(255) NOT NULL COMMENT '名前',
  `update_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時',
  `create_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `delete_datetime` DATETIME NULL DEFAULT NULL COMMENT '削除日時',
  `delete_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4 COLLATE=utf8mb4_general_ci
COMMENT = 'テスト';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
